# Site settings
title: "Hash Network"
description: "Welcome to the Hash Network GitHub Pages site!"
baseurl: ""  # Set to empty if your repo is directly hosted under your username (e.g., username.github.io)
url: "https://hashnetwork.github.io"  # Replace with your actual GitHub Pages URL

# Permalinks (optional: configure how URLs for posts and pages should appear)
# permalink: pretty  # Example: /year/month/day/title

# Build settings
paginate: 5
paginate_path: "/blog/page:num/"


defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
      
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-last-modified-at
